Modified the Simplified Chinese [zh-Hans] and added Traditional Chinese [zh-Hant] translation
Deltik/SignEdit pull request #13
Opened 2020-03-05 11:55 UTC by AobiYT

Hi, I've modified the Simplified Chinese [zh-Hans] and added Traditional Chinese [zh-Hant] translation to the resources folder, to include in the predefined translations.

**If only ONE zh translation can be added, use the Simplified Chinese one by changing the language tag from `zh-Hans` to `zh`, or else the original `zh` translation will be replaced.**

Note: I made a mistake by including "# 2" (which is an closed issue) in the title of some commit changes, please ignore it.

2020-03-05 16:07 UTC, Deltik requested changes
Did you intend for there to be literal spaces here?  If so, those spaces have to be escaped with `\\`.

2020-03-05 16:07 UTC, Deltik commented on src/resources/Comms_zh-CN.properties
> +print_line= {0}＜{1,number}＞{reset} {2}
The prepended space here will be ignored.  If you intended for there to be a literal space, it needs to be changed to this:
```suggestion
print_line=\\ {0}＜{1,number}＞{reset} {2}
```

2020-03-05 16:07 UTC, Deltik commented on src/resources/Comms_zh-Hant.properties
> +print_line= {0}＜{1,number}＞{reset} {2}
The prepended space here will be ignored.  If you intended for there to be a literal space, it needs to be changed to this:
```suggestion
print_line=\\ {0}＜{1,number}＞{reset} {2}
```

2020-03-05 16:07 UTC, Deltik commented on src/resources/Comms_zh-CN.properties
> +right_click_sign_to_apply_action_hint= {italic}右键点击要编辑的告示牌
The prepended space here will be ignored.  If you intended for there to be a literal space, it needs to be changed to this:
```suggestion
right_click_sign_to_apply_action_hint=\\ {italic}右键点击要编辑的告示牌
```

2020-03-05 16:07 UTC, Deltik commented on src/resources/Comms_zh-Hant.properties
> +right_click_sign_to_apply_action_hint= {italic}右鍵點擊要編輯的告示牌
The prepended space here will be ignored.  If you intended for there to be a literal space, it needs to be changed to this:
```suggestion
right_click_sign_to_apply_action_hint=\\ {italic}右鍵點擊要編輯的告示牌
```

2020-03-05 17:21 UTC, AobiYT commented
> Did you intend for there to be literal spaces here? If so, those spaces have to be escaped with `\\`.

_(This reply applies to all change request)_
Yes I was intended for it. However, when I test the translation file in my server, the double backslash here will cause a issue as shown below:
<img width="496" alt="2020-03-05_19 47 58" src="https://user-images.githubusercontent.com/48596398/76004503-8ad74500-5f44-11ea-8de2-1997c9f2d5a2.png">

But the issue can be solved by using only one backslash as shown below (idk why):
<img width="496" alt="螢幕擷取畫面 (140)" src="https://user-images.githubusercontent.com/48596398/76005573-2f0dbb80-5f46-11ea-923b-3b4983eb16ae.png">

btw I will still commit your suggestion for now. Thanks for your suggestion.
Note: It's now 1am already for me.

2020-03-05 18:16 UTC, merged

2020-03-05 18:40 UTC, Deltik commented
Thank you for the contribution!  It is live now as [SignEdit v1.11.4](https://github.com/Deltik/SignEdit/releases/tag/v1.11.4)!

----

The double backslashes didn't seem to cause any literal backslashes in my build.

2020-03-06 02:03 UTC, AobiYT commented
Thanks, but it seems you forgot the zh-TW one.

2020-03-06 02:23 UTC, AobiYT commented
Nice